# -*- coding: utf-8 -*-
"""Invoice_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTgnmFW97kfIAFlJ2HjJBaeJPIIU-uF0
"""

import numpy as np
import pandas as pd

data = pd.read_csv('invoices.csv')

data.info()

data.head(20)

data['full_name'] = data['first_name'] + ' ' + data['last_name']
display(data.head())

data.shape

num_distinct_emails = data['email'].nunique()
print(f"Number of distinct emails: {num_distinct_emails}")

num_distinct_products = data['product_id'].nunique()
print(f"Number of unique products: {num_distinct_products}")

data['total_amount'] = data['qty'] * data['amount']
display(data.head())

invoice_details_df = data[['product_id', 'qty', 'amount', 'invoice_date', 'total_amount']]
display(invoice_details_df.head())

invoice_details_df['invoice_date'] = pd.to_datetime(invoice_details_df['invoice_date'], format='%d/%m/%Y')
invoice_details_df = invoice_details_df.sort_values(by='invoice_date')
display(invoice_details_df.head())

invoice_details_df.head(10)

invoice_details_df.tail(10)

invoice_details_df['invoice_year'] = invoice_details_df['invoice_date'].dt.year
display(invoice_details_df.head())

product_yearly_total = invoice_details_df.groupby(['product_id', 'invoice_year'])['total_amount'].sum().reset_index()
display(product_yearly_total.head())

product_yearly_total.tail()



# Filter the product_yearly_total DataFrame for the years 1970-1975
years_to_consider = range(1970, 1976)
filtered_data = product_yearly_total[product_yearly_total['invoice_year'].isin(years_to_consider)]

# Group by year and select the top 5 products for each year
top_5_products_per_year = filtered_data.groupby('invoice_year').apply(lambda x: x.nlargest(5, 'total_amount')).reset_index(drop=True)

display(top_5_products_per_year)

products_1970_sorted = product_yearly_total[product_yearly_total['invoice_year'] == 1970].sort_values(by='total_amount', ascending=False)
display(products_1970_sorted)

invoice_details_df.head(20)



products_bought_daily = invoice_details_df.groupby('invoice_date')['product_id'].count().reset_index()
products_bought_daily.columns = ['invoice_date', 'number_of_products_bought']

# Sort by date to ensure the output starts from 1970 as requested implicitly by the original dataframe
products_bought_daily = products_bought_daily.sort_values(by='invoice_date')

display(products_bought_daily.head())

products_bought_daily.head(50)



import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(data=products_bought_daily, x='invoice_date', y='number_of_products_bought')
plt.title('Daily Number of Products Bought')
plt.ylabel('Number of Products Bought')
plt.xticks([]) # Remove x-axis tick labels
plt.xlabel('') # Remove x-axis label
plt.grid(True)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(data=products_bought_yearly, x='invoice_year', y='total_products_bought', marker='o')
plt.title('Total Products Bought Per Year (Continuous)')
plt.xlabel('Year')
plt.ylabel('Total Products Bought')
plt.xticks(rotation=45) # Rotate x-axis labels for better readability
plt.grid(True)
plt.tight_layout()
plt.show()

products_bought_yearly = invoice_details_df.groupby('invoice_year')['qty'].sum().reset_index()
products_bought_yearly.columns = ['invoice_year', 'total_products_bought']
display(products_bought_yearly.head())

min_date = invoice_details_df['invoice_date'].min()
max_date = invoice_details_df['invoice_date'].max()
full_date_range = pd.date_range(start=min_date, end=max_date, freq='D')

products_bought_daily_continuous = products_bought_daily.set_index('invoice_date').reindex(full_date_range, fill_value=0).reset_index()
products_bought_daily_continuous.columns = ['invoice_date', 'number_of_products_bought']

display(products_bought_daily_continuous.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(data=products_bought_daily_continuous, x='invoice_date', y='number_of_products_bought', marker='o') # Added marker='o'
plt.title('Daily Number of Products Bought (Continuous)')
plt.ylabel('Number of Products Bought')
plt.xticks([]) # Remove x-axis tick labels
plt.xlabel('') # Remove x-axis label
plt.grid(True)
plt.tight_layout()
plt.show()



"""Please enter the `product_id` you'd like to analyze. You can choose any product ID between 100 and 199, as there are 100 distinct products."""

#@title Enter Product ID
specific_product_id = 100 #@param {type:"integer"}

product_sales_yearly = product_yearly_total[product_yearly_total['product_id'] == specific_product_id]
display(product_sales_yearly.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(data=product_sales_yearly, x='invoice_year', y='total_amount', marker='o')
plt.title(f'Total Sales for Product ID {specific_product_id} Per Year')
plt.xlabel('Year')
plt.ylabel('Total Sales Amount')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

sales_1970 = invoice_details_df[invoice_details_df['invoice_year'] == 1970]

daily_sales_1970 = sales_1970.groupby('invoice_date')['total_amount'].sum().reset_index()
daily_sales_1970.columns = ['invoice_date', 'total_daily_sales']

# Create a continuous date range for 1970
min_date_1970 = daily_sales_1970['invoice_date'].min()
max_date_1970 = daily_sales_1970['invoice_date'].max()
full_date_range_1970 = pd.date_range(start=min_date_1970, end=max_date_1970, freq='D')

daily_sales_1970_continuous = daily_sales_1970.set_index('invoice_date').reindex(full_date_range_1970, fill_value=0).reset_index()
daily_sales_1970_continuous.columns = ['invoice_date', 'total_daily_sales']

display(daily_sales_1970_continuous.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.lineplot(data=daily_sales_1970_continuous, x='invoice_date', y='total_daily_sales', marker='o')
plt.title('Daily Total Sales for Year 1970 (Continuous)')
plt.ylabel('Total Daily Sales')
plt.xlabel('Date (1970)')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()